config:
  digitalocean:token:
    secure: AAABAPndPCfa240aqZ5mfeMD7TxtzRKdNGOZOhFLjyzRVWkK1qtQHxWkZ5k14+vvA1KZU9jF5AWhfZoR49kxoUdpD3jtcd4xRx96hDNdrqttmzVKo7xcNnc2J2ZNZIpdG+Mi/hrxVw==
  peach-clone-infra:sshKeyName: peach
